<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHv1DbAs\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHv1DbAs/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHv1DbAs.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHv1DbAs\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHv1DbAs\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hv1DbAs',
    'container.build_id' => '3d7ebc0e',
    'container.build_time' => 1575385066,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHv1DbAs');
